### ISSUE TITLE
scale-data-grid does not work under Vue3

### ISSUE THREAD

**Issue by Lumixnick** [telekom/scale#1414]
**Scale Version**
3.0.0-beta.112

**Framework and version**
Vue 3.2.45
**Code Reproduction**
https://codesandbox.io/s/red-river-ccp28t

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.0.1
 - Browser Chrome 
 - Version Version 107.0.5304.110 (Offizieller Build) (x86_64)

**Additional context**
This is a smart example to try the integration of scale-data-grid.
I tried several configurations and versions. Up to the telekom-scale 3.0.0-beta.112 the following error happens:
As of version 113 - latest, the function defineCustomElements() can no longer be used

`TypeError: Cannot read properties of undefined (reading 'length')
    at DataGrid.rowsHandler (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/scale-data-grid.entry.js:456:19)
    at DataGrid.componentWillLoad (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/scale-data-grid.entry.js:423:10)
    at safeCall (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/index-f2e5998d.js:1039:30)
    at dispatchHooks (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/index-f2e5998d.js:919:17)
    at Array.dispatch (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/index-f2e5998d.js:903:26)
    at consume (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/index-f2e5998d.js:1632:15)
    at flush (https://ccp28t.csb.app/node_modules/@telekom/scale-components/dist/esm/index-f2e5998d.js:1642:5) 
`

**Comment by Lumixnick** [comment]
Hello @niclas18,

I think then I have a problem. When I created the support request, my app was still in Java-Script with webpack. 
Now I've switched it to Vite AND Typescript. If I <script setup> as you use with the composition api , the scal-data-grid works properly.
If i do it in the way as follow, the i became the same failure. 

`<script lang="ts">
import { defineComponent, ref, computed } from "vue";
import { ScaleDataGrid } from "@telekom/scale-components/dist/components/scale-data-grid";

export default defineComponent({
  name: "ToolMainComponent",
  components: {},
  setup() {
    if (!customElements.get("custom-scale-data-grid")) {
      customElements.define("custom-scale-data-grid", ScaleDataGrid);

      const fields = [
        {
          type: "text",
          label: "Service",
          style: "checkbox",
          sortable: true,
        },
        {
          type: "text",
          label: "MS-githash",
          style: "switch",
          sortable: true,
        },
        {
          type: "text",
          label: "RC-githash",
          style: "switch",
          sortable: true,
        },
        {
          type: "checkbox",
          label: "Editable Switch",
          style: "checkbox",
          editable: false,
          sortable: true,
        },
      ];
      const rows = [
        ["AA", "BB", "CA", false],
        ["AA", "BB", "CC", true],
        ["AA", "BB", "CC", false],
        ["AA", "BB", "CD", true],
      ];
      return {
        rows,
        fields,
      };
    }
  },
});
</script>`

**Comment by felix-ico** [comment]
Hello @Lumixnick, 

I have already answered you by email but just for the sake of transparency (and maybe it will help somebody else) I will also post an answer here. 

>What's wrong with using the isCustomElement function in vue.config.js

I think the issue here is that vue.config.js is not supported by codesandbox because the project is not run with Vue CLI.

>Cannot read properties of undefined (reading 'length') at DataGrid.rowsHandler

I believe the problem is that rows and fields are defined in the submitForm method in DataGrid.vue, so there are no rows and fields for the DataGrid to render when it tries to mount initially. Defining the rows and fields in the `mounted` lifecycle function should solve the issue.

**Comment by Lumixnick** [comment]
Hello @felix-ico ,
i've forked the example from niclas18 and have added the scale-app-shield.
It is a simple example with vite and JS.
[https://stackblitz.com/edit/vitejs-vite-cbglfx?file=src%2Fmain.js,src%2FApp.vue,index.html](url)

- When you open the url for the first time, the scale-data-grid is displayed.
- If you then press refresh on the right side of the web container, the scale-data-grid disappears.
- After that, it depends on the screen size whether the scale-data-grid is displayed or not. This is suboptimal.

Attached is a screen video.
[Bildschirmaufnahme 2023-01-11 um 12.27.58.zip](https://github.com/telekom/scale/files/10392122/Bildschirmaufnahme.2023-01-11.um.12.27.58.zip)
