### ISSUE TITLE
ScaleDropdown crashes when changing options dynamically

### ISSUE THREAD

**Issue by tschinski** [telekom/scale#1661]
**Scale Version**
"@telekom/scale-components": "3.0.0-beta.116",
"@telekom/scale-components-react": "3.0.0-beta.116",

**Framework and version**
"react": "^18.2.0",
"react-dom": "^18.2.0",

**Current Behavior**
ScaleDropdown crashes when changing options dynamically

**Expected Behavior**
It is possible to change options dynamically and the Dropdown rerenders options accordingly.

**Code Reproduction**
```
const [options, setOptions] = useState<number[]>([1, 2]);
<ScaleDropdown>
       {options.map((option: number) => (
          <option value={option} key={option}>
            {option}
          </option>
        ))}
</ScaleDropdown>
<button onClick={() => setOptions([3, 4])}>Change options</button>
```

**Stack**

react-dom.development.js:22839 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:3000/WBFE/static/js/bundle.js:173390:22)
    at commitDeletionEffectsOnFiber (http://localhost:3000/WBFE/static/js/bundle.js:184425:19)
    at commitDeletionEffects (http://localhost:3000/WBFE/static/js/bundle.js:184379:9)
    at recursivelyTraverseMutationEffects (http://localhost:3000/WBFE/static/js/bundle.js:184617:13)
    at commitMutationEffectsOnFiber (http://localhost:3000/WBFE/static/js/bundle.js:184691:13)
    at recursivelyTraverseMutationEffects (http://localhost:3000/WBFE/static/js/bundle.js:184628:11)
    at commitMutationEffectsOnFiber (http://localhost:3000/WBFE/static/js/bundle.js:184680:13)
    at recursivelyTraverseMutationEffects (http://localhost:3000/WBFE/static/js/bundle.js:184628:11)
    at commitMutationEffectsOnFiber (http://localhost:3000/WBFE/static/js/bundle.js:184646:13)
    at recursivelyTraverseMutationEffects (http://localhost:3000/WBFE/static/js/bundle.js:184628:11)

react-dom.development.js:18687 The above error occurred in the <option> component:
    at option
    at scale-dropdown
    at ReactComponent (http://localhost:3000/WBFE/static/js/bundle.js:118974:7)
    at ScaleDropdown
    at div

**Comment by acstll** [comment]
@tschinski thanks for reporting. This is known issue with React (almost impossible to fix). Would it be possible for you to use the new [Dropdown Select](https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard) which does not suffer from this?

**Comment by georgwittberger-telekom-mms** [comment]
I am working on the project that @tschinski created this issue for. We migrated to "Dropdown Select" a while ago. Therefore, we would not need any solution for the deprecated "Dropdown" anymore. Feel free to close this issue as "won't fix".
