### ISSUE TITLE
ScaleFlyoutItem: Cannot read properties of undefined (reading 'focus')

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#813]
Hello there, 

the ScaleFlyout in ScaleAppHeader is throwing some erros
After closing the Menu

Version: beta 43,
Framework: React without React-Wrapper

The HTML
```html
<div slot="menu-icon">
  <scale-menu-flyout class="hydrated">
    <scale-nav-icon slot="trigger" icon="user-file-user" class="hydrated">
      <!---->
      <li class="meta-navigation__item">
        <a class="meta-navigation__item-link" href="javascript:void(0);">
          <scale-icon-user-file-user
            class="meta-navigation__item-link-icon hydrated"
            size="24"
            style="display: inline-flex"
          >
            <svg
              class="scale-icon"
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
            >
              <g fill="currentColor">
                <g>
                  <path
                    d="M8.9 16.5l3.1 3.1 3.1-3.1h2.25c2.35 0 4.3 1.65 4.7 3.95l.2 1.05H1.8l.15-1.05c.4-2.3 2.35-3.95 4.7-3.95zM12 2c3.5 0 6 2.5 6 6 0 3.4-2.4 7-6 7s-6-3.6-6-7c0-3.5 2.5-6 6-6zm0 1.5C9.4 3.5 7.5 5.4 7.5 8c0 2.65 1.8 5.5 4.5 5.5s4.5-2.85 4.5-5.5c0-2.6-1.9-4.5-4.5-4.5z"
                    fill-rule="evenodd"
                  ></path>
                </g>
              </g></svg></scale-icon-user-file-user
          ><span class="meta-navigation__item-label">Einstellungen</span></a
        >
      </li></scale-nav-icon
    ><scale-menu-flyout-list
      role="menu"
      class="hydrated"
      active=""
      style="top: 71.5px; left: 1086.05px; height: 56px; width: 111.953px"
      ><scale-menu-flyout-item
        role="menuitem"
        tabindex="-1"
        class="hydrated"
        aria-haspopup="true"
        aria-expanded="false"
        >Design ändern<scale-menu-flyout-list
          slot="sublist"
          role="menu"
          class="hydrated"
          style="top: 151.5px; left: 1022.73px; height: 42.1562px; width: 175.266px"
          ><scale-menu-flyout-item
            checkable="radio"
            checked=""
            role="menuitemradio"
            aria-checked="true"
            tabindex="-1"
            class="hydrated"
            >Von Windows übernehmen</scale-menu-flyout-item
          ><scale-menu-flyout-item
            checkable="radio"
            checked="false"
            role="menuitemradio"
            aria-checked="false"
            tabindex="-1"
            class="hydrated"
            >Helles Design</scale-menu-flyout-item
          ><scale-menu-flyout-item
            checkable="radio"
            checked="false"
            role="menuitemradio"
            aria-checked="false"
            tabindex="-1"
            class="hydrated"
            >Dunkles Design</scale-menu-flyout-item
          ></scale-menu-flyout-list
        ></scale-menu-flyout-item
      ></scale-menu-flyout-list
    ></scale-menu-flyout
  >
</div>

```

Stacktrace
```bash
TypeError: Cannot read properties of undefined (reading 'focus')
    at Header.handleCloseUserMenu (scale-app-header.entry.js?1caa:58:1)
    at HostElement.eval (index-f2e5998d.js?737d:51:1)
    at emitEvent (index-f2e5998d.js?737d:1074:1)
    at Object.emit (index-f2e5998d.js?737d:1063:1)
    at emitEvent (utils-524c237e.js?e7c0:61:1)
    at MenuFlyoutList.close (app-logo_11.entry.js?0706:448:16)
    at eval (index-f2e5998d.js?737d:1559:1)
    at async eval (app-logo_11.entry.js?0706:380:1)
```

ScaleAppHeader
```js
  handleCloseUserMenu() {
    this.userMenuToggle.focus();
    this.userMenu = false;
  }
```

**Comment by christopherGdynia** [comment]
Addition:

MenuFlyoutList
```js
async close(silent = false) {
    if (this.active && silent !== true) {
      emitEvent(this, 'scaleClose', { list: this.hostElement });
    }
    this.opened = false;
  }
```

**Comment by H4CK3R-01** [comment]
Same Problem here with Vue3 and Scale beta 46:
```
TypeError: Cannot read properties of undefined (reading 'focus')
    at d.handleCloseUserMenu (scale-app-header.entry.js:58:25)
    at HTMLElement.<anonymous> (index-f2e5998d.js:51:40)
    at ye (index-f2e5998d.js:1074:9)
    at Object.emit (index-f2e5998d.js:1063:20)
    at r (utils-524c237e.js:61:35)
    at C.close (app-logo_11.entry.js:448:7)
    at index-f2e5998d.js:1559:86
    at async app-logo_11.entry.js:379:31 undefined
```

**Comment by nowseemee** [comment]
This was fixed in February. Thanks for reporting @christopherGdynia and thanks for fixing @acstll!
